### ISSUE TITLE
Add a "Reverse Direction" setting to the Open/Close trait

### ISSUE THREAD

**Issue by mbudnek** [mbudnek/google-home-hubitat-community#26]
**Is your feature request related to a problem? Please describe.**
Some window shade drivers use their position attribute to denote the percent of the way they're extended, so 0 is fully open and 100 is fully closed.

**Describe the solution you'd like**
Add a "Reverse Direction" setting to the Open/Close trait to support these devices.

**Additional context**
In particular, this is in reference to [this driver](https://community.hubitat.com/t/ikea-blinds/17374/120) for Ikea's Fyrtur zigbee blinds.

**Comment by mattiaskagstrom** [comment]
yep, this would be nice. "Open the blind" now closes it and vise versa

**Comment by ryancasler** [comment]
Just noticed this.  I wrote that driver and I did it completely in the blind (pun intended) since I don't own any Fyrtur blinds.  So, I was just going by what folks told me was happening with them.  it appears that Ikea actually uses a reverse system for their blinds where 0 is completely open and 100 is completely closed (or unrolled).  There was work done to modify the driver to reverse the value of the percentage so that it would report it the opposite way, 0 being completely closed and 100% being completely open.  This driver has it configurable from one to the other.  Sorry I didn't notice this earlier or I would have pointed this out. 

https://gist.github.com/MorningZ/87f29c57bd4b6d45df8df33b65187eb0
