### ISSUE TITLE
Error when syncing a device

### ISSUE THREAD

**Issue by StrangledSyntax** [mbudnek/google-home-hubitat-community#57]
**Describe the bug**
Getting the following error when trying to sync new "Fan" device into the app. I already have multiple devices setup and running in the app. I just can't add anything new.n I will attach a screen shot from the Hubitat log.

java.lang.NullPointerException: Cannot invoke method split() on null object on line 2149 (handleAction)

Hubitat Elevation® Platform Version
2.2.5.131
Hardware Version
Rev C-7
On last app release on Jan 31 2021

<img width="835" alt="Untitled" src="https://user-images.githubusercontent.com/78987970/107832837-b6ff6680-6d4e-11eb-9376-9c37c6287363.png">

**Comment by mbudnek** [comment]
It looks like it's complaining that the "Google Level Names" setting for one or more of your fan speeds isn't set.  Check the Fan Speed traits on your fan device types and make sure each configured speed has a name.

**Comment by StrangledSyntax** [comment]
Huh, I just reversed the order of the device traits and it let me add it into the Google Home app.

Fan Speed
On/Off

Thanks for your help and this awesome integration.

**Comment by mbudnek** [comment]
Huh.  My guess is that something must have just not gotten saved properly and deleting and re-adding the trait prompted it to save the settings correctly.

Since you've got it working correctly I'm going to close this issue.  If the problem pops back up feel free to leave another comment here and I'll re-open it and investigate more deeply.
