### ISSUE TITLE
OAuth info for Hubitat Package Manager version

### ISSUE THREAD

**Issue by shanelord01** [mbudnek/google-home-hubitat-community#85]
I’ve installed this via Hubitat Package Manager. 

How do I get the ClientID and Client Secret codes for OAuth setup?

**Comment by mbudnek** [comment]
It's the same process as if you installed the app manually.  Go to "Apps Code", find "Google Home Community", and click "OAuth" in the top-right corner of the page.

**Comment by shanelord01** [comment]
> It's the same process as if you installed the app manually. Go to "Apps Code", find "Google Home Community", and click "OAuth" in the top-right corner of the page.

Thanks - got it working. It's easier to find the OAuth button while importing your own code - less obvious when using HPM.

**Comment by mbudnek** [comment]
Yeah, HPM has an option to enable OAuth, but actually needing to copy the client ID and secret is unusual enough that it doesn't provide a way to access them.

I'm going to go ahead and close this issue since it sounds like you have things working.  Feel free to open another if you have any other problems.
