### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ryancasler** [mbudnek/google-home-hubitat-community#9]
Followed the instructions to the letter 3 separate times and every time I get the same error.  Failed to update setting.  Please check connection.  My phone has a stable wifi connection so I don't know what the problem is.

**Comment by mbudnek** [comment]
The most common causes for errors like that are either trying to link to Google Home with no devices selected or configuration problems within the Google Action. Make sure you have at least one device selected when linking. If you do, check your Fulfillment URL in the Action; it should look something like `https://cloud.hubitat.com/api/c1776b22-f9fe-44b9-ac49-93e5adefd672/apps/254/action`, where `c1776b22-f9fe-44b9-ac49-93e5adefd672` is your Hub ID and `254` is the app instance ID.

If neither of those fix your problem, turn on debug logging in the Google Home Community app and watch the Hubitat log while linking. You should see a line like `{inputs=[{intent=action.devices.SYNC}], requestId=9516322382727038343}`. If you see that then the Action is likely configured correctly. If you don't then the issue is likely on the Action side.

**Comment by mbudnek** [comment]
I believe this has been resolved over in the [Hubitat forum thread](https://community.hubitat.com/t/alpha-community-maintained-google-home-integration/34957).
